import styles from '@/styles/Home.module.css';
import { Geist, Geist_Mono } from 'next/font/google';
import Head from 'next/head';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='keywords' content='blog, hunterblog, coding blog'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={styles.imageWrap}>
          <img
            className={styles.img}
            src='/homeimg.jpg'
            alt='Homeimage'
            width={150}
            height={145}
          ></img>
        </div>
        <h1 className={styles.h1}>&lt;Hunting Coder /&gt;</h1>
        <div className={styles.blogs}>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className={`${styles.blog}`}>
            <h3 className={styles.h3}>How to learn Javascript in 2025</h3>
            <p className={styles.p}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea,
              libero? Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Iste eos tenetur facere facilis ipsam id soluta autem qui repellat
              laboriosam.
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div className={`${styles.blog}`}>
            <h3 className={styles.h3}>How to learn react in 2025</h3>
            <p className={styles.p}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio, porro?
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div className={`${styles.blog}`}>
            <h3 className={styles.h3}>How to learn nextjs in 2025</h3>
            <p className={styles.p}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Distinctio, porro?
            </p>
            <button className={styles.btn}>Read more</button>
          </div>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
