import styles from '@/styles/Home.module.css';
import { Geist, Geist_Mono } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='keywords' content='blog, hunterblog, coding blog'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      {/* <style jsx>
            {`
              h1 {
                color: #0070f3;
              }
            `}
          </style> */}
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        {/* <Dummy /> */}
        <nav className={`${styles['main-nav']}`}>
          <ul>
            <Link href='/'>
              <li>Home</li>
            </Link>
            <Link href='/about'>
              <li>About</li>
            </Link>
            <Link href='/blogs'>
              <li>Blogs</li>
            </Link>
            <Link href='/contact'>
              <li>Contact</li>
            </Link>
          </ul>
        </nav>
        <main className={styles.main}>
          <h1>Hunting Coder</h1>
          <p>A Blog for coders by a coder</p>
          {/* <div className={`${styles1.con} ${styles2.con}`}> */}
          <div>
            <h2>Popular Blogs</h2>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
          </div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
