import styles from '@/styles/Home.module.css';
import { Geist, Geist_Mono } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='keywords' content='blog, hunterblog, coding blog'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1>Hunting Coder</h1>
          <Image
            src='/homeimg.jpg'
            alt='Homeimage'
            width={518}
            height={345}
          ></Image>
          <p>A Blog for coders by a coder</p>
          <div>
            <h2>Popular Blogs</h2>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
            <div className={`${styles.blog}`}>
              <h3>This is heading for the blog post</h3>
              <p>Short Description of blog post</p>
            </div>
          </div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
